
export const ADD_GAME = 'ADD_GAME';
export const REMOVE_GAME = 'REMOVE_GAME';
export const COMPLETE_TRADE = 'COMPLETE_TRADE';
export const DECLINE_TRADE = 'DECLINE_TRADE';
export const GET_USER_GAMES = 'GET_USER_GAMES';
export const GET_USER_REQUESTS = 'GET_USER_REQUESTS';
export const CLEAR_USER_REQUESTS = 'CLEAR_USER_REQUESTS';
export const ADD_REQUEST = 'ADD_REQUEST';
export const REMOVE_REQUEST = 'REMOVE_REQUEST';
export const CLEAR_USER_GAMES = 'CLEAR_USER_GAMES';