export const OUTGOING = 'outgoing';
export const INCOMING = 'incoming';
export const PENDING = 'Pending';
export const ACCEPTED = 'Accepted';
export const DECLINED = 'Declined';
export const CANCELLED = 'Cancelled';
export const CANCEL_TRADE = 'Cancel Offer';
export const ACCEPT_TRADE = 'Accept Trade';
export const DECLINE_TRADE_OFFER = 'Decline Trade';